(deftheme pretty
  "Created 2015-04-01.")

(custom-theme-set-faces
 'pretty
 '(cursor ((t (:background "#2196F3"))))
 '(escape-glyph ((t (:foreground "#E91E63"))))
 '(minibuffer-prompt ((t (:background "#5677FC" :foreground "#FAFAFA"))))
 '(highlight ((t (:background "#E1F5FE"))))
 '(region ((t (:background "#EDE7F6" :distant-foreground "#EDE7F6"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#FFEB3B"))))
 '(trailing-whitespace ((t (:background "#F44336"))))
 '(font-lock-builtin-face ((t (:foreground "#0097A7"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#9E9E9E"))))
 '(font-lock-constant-face ((t (:foreground "#512DA8"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face))))
 '(font-lock-function-name-face ((t (:foreground "#880E4F"))))
 '(font-lock-keyword-face ((t (:foreground "#607D8B"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#C51162"))))
 '(font-lock-regexp-grouping-construct ((t (:inherit font-lock-regexp-grouping-backslash))))
 '(font-lock-string-face ((t (:foreground "#4CAF50"))))
 '(font-lock-type-face ((t (:foreground "#9C27B0"))))
 '(font-lock-variable-name-face ((t (:foreground "#03A9F4"))))
 '(font-lock-warning-face ((t (:foreground "#e51c23" :underline (:color foreground-color :style wave)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "RoyalBlue3"))))
 '(link-visited ((t (:foreground "magenta4" :inherit (link)))))
 '(fringe ((t (:background "#E0E0E0"))))
 '(header-line ((t (:box nil :foreground "grey20" :background "grey90" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:background "#5677FC" :foreground "#ffffff" :box nil))))
 '(mode-line-buffer-id ((t (:weight extra-bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "#B3E5FC" :foreground "#212121"))))
 '(isearch ((t (:background "#CFD8DC"))))
 '(isearch-fail ((t (:background "#F8BBD0"))))
 '(lazy-highlight ((t (:background "#BBDEFB"))))
 '(match ((t (:background "#FFF9C4"))))
 '(next-error ((t (:inherit region))))
 '(query-replace ((t (:inherit isearch))))
 '(linum ((t (:background "#E0E0E0" :foreground "#616161" :weight light :width condensed))))
 '(window-divider ((t (:foreground "#E0E0E0"))))
 '(default ((t (:background "#fafafa" :foreground "#212121"))))
 '(window-divider-last-pixel ((t (:foreground "#E0E0E0"))))
 '(window-divider-first-pixel ((t (:foreground "#E0E0E0")))))

(provide-theme 'pretty)
